version: '3.7'
services:
  passbolt_db:
    image: mariadb:10.3
    env_file:
      - env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == amrc-factoryP-1
    networks:
      - factory-plus

  passbolt:
    image: passbolt/passbolt:2.13.5-debian
    tty: true
    depends_on:
      - passbolt_db
    env_file:
      - env/passbolt.env
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "-t", "0", "passbolt_db:3306", "--", "/docker-entrypoint.sh"]
    deploy:
      placement:
        constraints:
          - node.hostname == amrc-factoryP-1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.passbolt.rule=Host(`passwords.amrc-factoryplus.<domain>`)"
        - "traefik.docker.network=factory-plus"
        - "traefik.http.services.passbolt.loadbalancer.server.port=80"
        - "traefik.http.routers.passbolt.tls=true"
    networks:
      - factory-plus

networks:
  factory-plus:
    external: true
    name: factory-plus

volumes:
  database_volume:
  gpg_volume:
  images_volume:
